spring.application.name=VendasService
spring.config.import=optional:configserver:
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.username=root
spring.cloud.config.password=root
spring.cloud.config.name=ms-venda
